---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
  namespace: ragaas
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/part-of: ragaas-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
