{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "qdrant.fullname" . }}
  namespace: {{ include "qdrant.namespace" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qdrant.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ include "qdrant.namespace" . }}
{{- end }}
