{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-credentials
  namespace: {{ include "monitoring.namespace" . }}
  labels:
    {{- include "monitoring.grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.adminUser | b64enc | quote }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
{{- end }}
