apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-credentials
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.config.defaultUser | b64enc | quote }}
  password: {{ .Values.config.defaultPass | b64enc | quote }}
  erlang-cookie: {{ .Values.config.erlangCookie | b64enc | quote }}
