apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
    {{- if .Values.metrics.enabled }}
    - port: 15692
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
